# config.yaml
experiments:


  - name: experiment_wavelet_m1_all_r
    select: 'last' #selection for duplicates timeseries
    filter:
      type: 'None'
      sampling_rate: 50
      cutoff: 5
    features:
      method: 'wavelet'
      type: 'haar'
      level: 6
    bubble:
      r: all
      m: 2

